# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  build:
    macos:
      xcode: 11.5.0 # Specify the Xcode version to use

    steps:
      - checkout
      - run: npm install
      - run: ./build-miniapps.sh $CIRCLE_BRANCH
      - run: npm run build-main 
      - run: npm run build-renderer
      - run: npm run package
